import Page from "@containers/page";
import '@styles/globals.scss'
import {I18nProviderClient} from "locales/client";
import {getStaticParams} from "locales/server";
import en from 'locales/translations/en';

import type {Metadata} from 'next'
import {setStaticParamsLocale} from "next-international/server";
import {Inter} from 'next/font/google'
import Script from "next/script";
import React, {Fragment} from "react";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Boilerplate NextJS Application',
    description: 'Generated by create next app',
}

export function generateStaticParams() {
    return getStaticParams();
}

export default function RootLayout({children}: { children: React.ReactNode }) {
    setStaticParamsLocale('en');

    return (
        <html lang="en">
        <I18nProviderClient fallbackLocale={en}>
            {process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS &&
                <Fragment>
                    <Script async
                            src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}`}/>
                    <Script id={'google-analytics-script'} dangerouslySetInnerHTML={{
                        __html: `window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}gtag('js', new Date());gtag('config', '${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}', {page_path: window.location.pathname,});`
                    }}/>
                </Fragment>
            }
            <body className={inter.className}>
            <Page>
                {children}
            </Page>
            </body>
        </I18nProviderClient>
        </html>
    )
}
